### ISSUE TITLE
QUESTION: Can this be refreshed?

### ISSUE THREAD

**Issue by tandrewnichols** [umaumax/vim-lcov#1]
First of all, I love the idea here.

I've followed the steps in the readme and have the missing coverage signs showing. Now if I add a new test that covers a new line . . . there seems to be no way to force a refresh of the signs. I tried rerunning `LcovVisible` and that doesn't seem to do anything.

**Comment by umaumax** [comment]
Thank you for using my plugin!  
  
I add refresh function at 52be6ce.

I think you can check this refresh function by following below step.

```
cd vim-lcov/autoload/samples/
rm -f *.gcda *.gcno
g++ -coverage -o main main.cpp
./main
lcov -c -b . -d . -o main_1.info
./main hello
lcov -c -b . -d . -o main_2.info
vim main.cpp
```

```
:LcovVisible ./main_1.info
:LcovVisible ./main_2.info
:LcovVisible ./main_1.info
```
